### ISSUE TITLE
Cannot find module './Aggregation'

### ISSUE THREAD

**Issue by aoreinoso** [bafolts/plantuml-code-generator#27]
...

Ciudad "1" o-- "many" Direccion
Ciudadano "1" *-- "many" Direccion

...

Error: Cannot find module './Aggregation'
Require stack:
- /home/aor/Descargas/plantuml-code-generator-master/src/plantuml.js
- /home/aor/Descargas/plantuml-code-generator-master/plantcode
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.Module._load (internal/modules/cjs/loader.js:928:27)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at peg$c44 (/home/aor/Descargas/plantuml-code-generator-master/src/plantuml.js:83:50)
    at peg$parseconnectortype (/home/aor/Descargas/plantuml-code-generator-master/src/plantuml.js:1594:18)
    at peg$parseconnectordeclaration (/home/aor/Descargas/plantuml-code-generator-master/src/plantuml.js:929:22)
    at peg$parseumlline (/home/aor/Descargas/plantuml-code-generator-master/src/plantuml.js:785:38)
    at peg$parseumllines (/home/aor/Descargas/plantuml-code-generator-master/src/plantuml.js:567:14)
    at peg$parseplantumlfile (/home/aor/Descargas/plantuml-code-generator-master/src/plantuml.js:415:22) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/aor/Descargas/plantuml-code-generator-master/src/plantuml.js',
    '/home/aor/Descargas/plantuml-code-generator-master/plantcode'
  ]
}

**Comment by sweethuman** [comment]
I am also having this issue

**Comment by bafolts** [comment]
What is the command run when this is seen?

**Comment by sweethuman** [comment]
`plantcode -l csharp class.puml` on this file

```plantuml
@startuml
'https://plantuml.com/class-diagram

class User{
+ String name
+ String email
+ String password
# Boolean paymentMade
}

class Author{
+ String affiliation
+ String webpage
}

class Listener{
}

class PCMember{
+ String affiliation
+ String webpage
# Proposal[] assignedProposals
}

class CommitteeUser{}

class Chairman{}

class Proposal{
+ String name
+ String[] keywords
+ String[] topics
+ Author[] authors
+ Abstract abstract
+ Paper paper
+ ProposalOpinion[] opinions
+ ProposalReview[] reviews
}

class Abstract{
+ String description
}

class Paper{
+ byteStream bytes
}

class Section{
+ String name
+ string room
+ PCMember sessionChair
+ Listener[] listeners
+ Proposal[] proposals
+ Event[] program
}

class Event{
+ Paper paper
+ Author speaker
+ Date date
}

class Conference{
+ String name
+ String description
+ Chairman chair
+ CommitteeUser[] coChairs
+ PCMember[] programCommittee
+ Date startDate
+ Date proposalDeadline
+ Date biddingDeadline
+ Date reviewDeadline
+ Date resultDeadline
+ Date improveDeadline
+ Date endDate
+ Section[] sections
}


class ProposalOpinion{
+ Proposal proposal
+ PCMember user
+ BidState bid
}


class ProposalReview {
+ Proposal proposal
+ PCMember user
+ ReviewState review
}

User <|-- Listener
User <|-- PCMember
User <|-- Author

PCMember <|-- Chairman
PCMember <|-- CommitteeUser


Proposal *-- Abstract : 1
Proposal *-- Paper : 0..1
Proposal o-- Author : 1..*
Proposal *-- ProposalOpinion: 0..*
Proposal *-- ProposalReview: 0..*

Conference *-- Chairman: 1
Conference *-- CommitteeUser: 0..*
Conference *-- PCMember: 0..*
Conference o-- Section : 1..*

Section o-- PCMember : 1
Section o-- Proposal : 1..*
Section *-- Event : 1..*

Event -- Author
Event -- Paper

ProposalOpinion -- BidState
'ProposalOpinion o-- Proposal : 1
'ProposalOpinion o-- PCMember : 1

ProposalReview -- ReviewState
@enduml
```
